networks:
  dev:
    driver: bridge

services:
  kukac-challenge-app:
    container_name: kukac
    ports:
      - "3002:3000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
